#!/bin/bash

read -p 'Attempt to log into a non-existing account'
curl -H "Content-Type: application/json" -X POST -d '{"username":"nonexisting", "password":"password"}' http://localhost:3000/login

read -p $'\nRegister an account'
curl -H "Content-Type: application/json" -X POST -d '{"username":"vincent", "password":"password", "firstname":"Vincent", "lastname":"Huor"}' http://localhost:3000/register

read -p $'\nTry to register the same (existing) account'
curl -H "Content-Type: application/json" -X POST -d '{"username":"vincent", "password":"password", "firstname":"Vincent", "lastname":"Huor"}' http://localhost:3000/register

read -p $'\nLog in to an account'
curl -H "Content-Type: application/json" -X POST -d '{"username":"vincent", "password":"password"}' http://localhost:3000/login --cookie-jar user1.cookie

read -p $'\nSearch for course CSC207H1F'
curl http://localhost:3000/search?course="CSC207H1F"

read -p $'\nCreate a new timetable'
curl http://localhost:3000/newtimetable

read -p $'\nAdd a course with two sections'
curl -H "Content-Type: application/json" -X POST -d '{"userid":"vincent", "data":[{"id":"course1","code":"course1","name":"Software Design","description":"An introduction to software design and development concepts, methods, and tools using a statically-typed object-oriented programming language such as Java. Topics from: version control, unit testing, refactoring, object-oriented design and development, design patterns, advanced IDE usage, regular expressions, and reflection.  Representation of \u001aoating-point numbers and introduction to numerical computation.","division":"Faculty of Arts and Science","department":"Computer Science","prerequisites":"60% or higher in CSC148H1/CSC150H1","exclusions":"","level":200,"campus":"UTSG","term":"2016 Fall",
    "meeting_sections":[
        {"code":"L0101","size":124,"enrolment":0,"times":[
            {"day":"TUESDAY","start":36000,"end":39600,"duration":3600,"location":"BA 1170"},{"day":"WEDNESDAY","start":36000,"end":39600,"duration":3600,"location":"BA 1170"},{"day":"FRIDAY","start":36000,"end":39600,"duration":3600,"location":"BA 1170"}],"instructors":["L Shorser"]},
        {"code":"L0201","size":130,"enrolment":0,"times":[
            {"day":"WEDNESDAY","start":43200,"end":46800,"duration":3600,"location":"RW 117"},{"day":"TUESDAY","start":50400,"end":54000,"duration":3600,"location":"RW 117"},{"day":"FRIDAY","start":43200,"end":46800,"duration":3600,"location":"RW 117"}],"instructors":["L Shorser"]}],
"breadths":[5]}]}' http://localhost:3000/addcourse

read -p $'\nAdd a course with two sections. One section is the same as the previous'
curl -H "Content-Type: application/json" -X POST -d '{"userid":"vincent", "data":[{"id":"course2","code":"course2","name":"Software Tools and Systems Programming","description":"Software techniques in a Unix-style environment, using scripting languages and a machine-oriented programming language (typically C). What goes on in the operating system when programs are executed. Core topics: creating and using software tools, pipes and filters, file processing, shell programming, processes, system calls, signals, basic network programming.","division":"Faculty of Arts and Science","department":"Computer Science","prerequisites":"CSC207H1","exclusions":"CSC372H1, CSC369H1, CSC469H1","level":200,"campus":"UTSG","term":"2016 Fall",
    "meeting_sections":[
        {"code":"L0101","size":124,"enrolment":0,"times":[
            {"day":"TUESDAY","start":36000,"end":39600,"duration":3600,"location":"BA 1170"},{"day":"WEDNESDAY","start":36000,"end":39600,"duration":3600,"location":"BA 1170"},{"day":"FRIDAY","start":36000,"end":39600,"duration":3600,"location":"BA 1170"}],"instructors":["L Shorser"]},
        {"code":"L0201","size":125,"enrolment":0,"times":[
            {"day":"TUESDAY","start":57600,"end":61200,"duration":3600,"location":"SS 2117"},{"day":"THURSDAY","start":57600,"end":61200,"duration":3600,"location":"SS 2117"}],"instructors":["M Barsky"]}],
"breadths":[5]}]}' http://localhost:3000/addcourse

read -p $'\nAdd a course with one section that does not fit'
curl -H "Content-Type: application/json" -X POST -d '{"userid":"vincent", "data":[{"id":"course3","code":"course3","name":"Software Tools and Systems Programming","description":"Software techniques in a Unix-style environment, using scripting languages and a machine-oriented programming language (typically C). What goes on in the operating system when programs are executed. Core topics: creating and using software tools, pipes and filters, file processing, shell programming, processes, system calls, signals, basic network programming.","division":"Faculty of Arts and Science","department":"Computer Science","prerequisites":"CSC207H1","exclusions":"CSC372H1, CSC369H1, CSC469H1","level":200,"campus":"UTSG","term":"2016 Fall",
    "meeting_sections":[
        {"code":"L0201","size":125,"enrolment":0,"times":[
            {"day":"TUESDAY","start":57600,"end":61200,"duration":3600,"location":"SS 2117"},{"day":"THURSDAY","start":57600,"end":61200,"duration":3600,"location":"SS 2117"}],"instructors":["M Barsky"]}],
"breadths":[5]}]}' http://localhost:3000/addcourse

read -p $'\nSave timetable'
curl -H "Content-Type: application/json" -X PUT -d '{"userid":"vincent"}' http://localhost:3000/savetimetable --cookie user1.cookie

read -p $'\nDeleting and loading a timetable'
read -p $'\nSince creating a new timetable generates a random identification, which is used in deleting and loading, it is not possible to use a cURL command to perform these functions. We do not know the unique id from the previous cURL commands. This is only possible when connecting the front and back end.'

read -p $'\nDelete course1'
curl -H "Content-Type: application/json" -X POST -d '{"userid":"vincent", "courseid":"course1"}' http://localhost:3000/removecourse

read -p $'\nDelete course2'
curl -H "Content-Type: application/json" -X POST -d '{"userid":"vincent", "courseid":"course2"}' http://localhost:3000/removecourse

read -p $'\nDelete course3'
curl -H "Content-Type: application/json" -X POST -d '{"userid":"vincent", "courseid":"course3"}' http://localhost:3000/removecourse

read -p $'\nLog out'
curl -H "Content-Type: application/json" -X POST -d '{"username":"vincent"}' http://localhost:3000/logout

read -p $'\nAdding a comment correctly'
curl -H "Content-Type: application/json" -X POST -d '{"email":"vincent", "comment": "I love your website"}' http://localhost:3000/addcomment

read -p $'\nAdding a comment incorrectly, expect 400 status'
curl -H "Content-Type: application/json" -X POST -d '{"email":"vincent"}' http://localhost:3000/addcomment

read -p $'\nAdding a comment incorrectly, expect 400 status'
curl -H "Content-Type: application/json" -X POST -d '{"comment": "I love your website"}' http://localhost:3000/addcomment

read -p $'\nAdding a comment incorrectly, expect 400 status'
curl -H "Content-Type: application/json" -X POST -d '{}' http://localhost:3000/addcomment

read -p $'\nRetrieving all comments'
curl http://localhost:3000/getcomment